[package]
name = "termAI"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.1"
crossterm = "0.28.1"
tokio = { version = "1", features = ["full"] }
rusqlite = { version = "0.32", features = ["bundled"] }
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
